#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit

check_kafka_availability() {
  echo "Checking for kafka availability"
  ping -c 2 kafka &> /dev/null
}

until check_kafka_availability; do
  >&2 echo 'Waiting for Kafka to become available...'
  sleep 1
done
>&2 echo 'Kafka is available'

python3 app/consumer.py
