"""empty message

Revision ID: 27ae614fc8ef
Revises: 6720e9479ba9
Create Date: 2021-08-24 15:25:49.144012

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "27ae614fc8ef"
down_revision = "6720e9479ba9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "type_subtype_index", "notification_template", ["type", "subtype"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("type_subtype_index", table_name="notification_template")
    # ### end Alembic commands ###
