"""empty message

Revision ID: 2e8c736e1390
Revises: 3732650e624f
Create Date: 2022-01-24 13:30:42.664743

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2e8c736e1390"
down_revision = "3732650e624f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_notification", sa.Column("reference", sa.String(), nullable=True)
    )
    op.alter_column(
        "email_notification", "message", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "email_notification", "message", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("email_notification", "reference")
    # ### end Alembic commands ###
