"""empty message

Revision ID: 41572c7c5c9a
Revises: 965f39b95db4
Create Date: 2022-01-25 12:25:12.912333

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "41572c7c5c9a"
down_revision = "965f39b95db4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "notification_template", ["template_file"])
    op.add_column(
        "sms_notification",
        sa.Column("message_subtype", sa.String(length=20), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sms_notification", "message_subtype")
    op.drop_constraint(None, "notification_template", type_="unique")
    # ### end Alembic commands ###
