"""empty message

Revision ID: 530544c36e6e
Revises: 93ba49d2decb
Create Date: 2021-07-26 11:37:01.210497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "530544c36e6e"
down_revision = "93ba49d2decb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification_template", sa.Column("message", sa.String(), nullable=True)
    )
    op.drop_column("notification_template", "template")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification_template",
        sa.Column("template", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("notification_template", "message")
    # ### end Alembic commands ###
