"""empty message

Revision ID: 6720e9479ba9
Revises: 70d2c2afd4ee
Create Date: 2021-07-26 12:25:20.405364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6720e9479ba9"
down_revision = "70d2c2afd4ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification_template", sa.Column("message", sa.String(), nullable=True)
    )
    op.drop_column("notification_template", "template")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification_template",
        sa.Column("template", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("notification_template", "message")
    # ### end Alembic commands ###
