"""empty message

Revision ID: 70d2c2afd4ee
Revises: 530544c36e6e
Create Date: 2021-07-26 12:18:51.705702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "70d2c2afd4ee"
down_revision = "530544c36e6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification_template", sa.Column("template", sa.String(), nullable=True)
    )
    op.add_column(
        "notification_template",
        sa.Column("template_keywords", sa.String(), nullable=True),
    )
    op.drop_column("notification_template", "keywords")
    op.drop_column("notification_template", "message")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification_template",
        sa.Column("message", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "notification_template",
        sa.Column("keywords", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("notification_template", "template_keywords")
    op.drop_column("notification_template", "template")
    # ### end Alembic commands ###
