"""empty message

Revision ID: 7566c4cd281a
Revises: 41572c7c5c9a
Create Date: 2022-01-25 12:36:34.566752

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7566c4cd281a"
down_revision = "41572c7c5c9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sms_notification", sa.Column("message_template", sa.String(), nullable=False)
    )
    op.alter_column(
        "sms_notification", "message", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sms_notification", "message", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("sms_notification", "message_template")
    # ### end Alembic commands ###
