"""empty message

Revision ID: 93ba49d2decb
Revises:
Create Date: 2021-07-21 11:44:44.032792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision = "93ba49d2decb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_template",
        sa.Column("id", UUID(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("subtype", sa.String(), nullable=True),
        sa.Column("template", sa.String(), nullable=True),
        sa.Column("keywords", sa.String(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sms_notification",
        sa.Column("id", UUID(), nullable=False),
        sa.Column("recipient", sa.String(length=15), nullable=False),
        sa.Column("message_type", sa.String(length=20), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("reference", sa.String(length=60), nullable=True),
        sa.Column("sms_client", sa.String(length=60), nullable=True),
        sa.Column("delivered_to_sms_client", sa.Boolean(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sms_notification")
    op.drop_table("notification_template")
    # ### end Alembic commands ###
