"""empty message

Revision ID: 965f39b95db4
Revises: 2e8c736e1390
Create Date: 2022-01-24 13:46:50.935170

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "965f39b95db4"
down_revision = "2e8c736e1390"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_notification", "message")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_notification",
        sa.Column("message", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
