"""empty message

Revision ID: b12db4c043bc
Revises: 
Create Date: 2021-06-20 22:38:35.109029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b12db4c043bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('recipient', sa.String(length=15), nullable=False),
    sa.Column('message_type', sa.Enum('otp', 'password_reset', 'notification', 'general', 'other', name='message_type'), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.Column('sms_client', sa.String(length=60), nullable=True),
    sa.Column('delivered_to_sms_client', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sms')
    # ### end Alembic commands ###
